# Generated by Django 4.1.1 on 2022-11-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=120)),
                ('section', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('c_name', models.CharField(max_length=120)),
                ('c_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_detail',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.classes')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.faculty_detail')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.course')),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('class_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.classes')),
                ('eight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eight_Hour', to='amsdb.subject')),
                ('fifth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fifth_Hour', to='amsdb.subject')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First_Hour', to='amsdb.subject')),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fourth_Hour', to='amsdb.subject')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Second_Hour', to='amsdb.subject')),
                ('seveen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seveen_Hour', to='amsdb.subject')),
                ('sixth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sixth_Hour', to='amsdb.subject')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Third_Hour', to='amsdb.subject')),
            ],
        ),
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('roll_no', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=120)),
                ('s_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amsdb.faculty_detail'),
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.CharField(max_length=120)),
                ('first', models.CharField(max_length=120)),
                ('second', models.CharField(max_length=120)),
                ('third', models.CharField(max_length=120)),
                ('fourth', models.CharField(max_length=120)),
                ('fifth', models.CharField(max_length=120)),
                ('sixth', models.CharField(max_length=120)),
                ('seveen', models.CharField(max_length=120)),
                ('eight', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.student_detail')),
                ('s_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.classes')),
            ],
        ),
    ]
