# Generated by Django 4.1 on 2022-10-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('c_name', models.CharField(max_length=120)),
                ('c_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('roll_no', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=120)),
                ('sem', models.CharField(max_length=120)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='faculty_details',
            new_name='faculty_detail',
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsdb.student_detail')),
            ],
        ),
    ]
