# Generated by Django 4.1.1 on 2022-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_detail',
            name='class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
