# Generated by Django 4.1.1 on 2022-10-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsdb', '0003_classes_subject_rename_sem_student_detail_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(default='ashwin', on_delete=django.db.models.deletion.PROTECT, to='amsdb.faculty_detail'),
            preserve_default=False,
        ),
    ]
