# Generated by Django 4.1.1 on 2022-10-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsdb', '0004_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
