# Generated by Django 4.1 on 2022-10-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsdb', '0005_alter_classes_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_student',
            field=models.CharField(max_length=100),
        ),
    ]
