# Generated by Django 4.1 on 2022-10-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsdb', '0006_alter_attendance_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
